// Mock data for testing Leave Management UI
export const mockLeaveRequests = [
  {
    _id: "1",
    name: "Liam",
    designation: "Senior Developer",
    image: undefined,
    startDate: "2026-02-21",
    endDate: "2026-02-21",
    leaveType: "Date",
    title: "Personal Leave",
    reason: "Personal appointments",
    status: "Pending" as const,
  },
  {
    _id: "2",
    name: "Mason",
    designation: "Product Manager",
    image: undefined,
    startDate: "2026-02-21",
    endDate: "2026-02-21",
    leaveType: "Date",
    title: "Sick Leave",
    reason: "Medical checkup",
    status: "Pending" as const,
  },
  {
    _id: "3",
    name: "Liam",
    designation: "Senior Developer",
    image: undefined,
    startDate: "2023-01-01",
    endDate: "2023-01-01",
    leaveType: "Date",
    title: "Casual Leave",
    reason: "Family commitment",
    status: "Pending" as const,
  },
  {
    _id: "4",
    name: "Liam",
    designation: "Senior Developer",
    image: undefined,
    startDate: "2023-01-01",
    endDate: "2023-01-01",
    leaveType: "Date",
    title: "Annual Leave",
    reason: "Vacation",
    status: "Pending" as const,
  },
  {
    _id: "5",
    name: "Mason",
    designation: "Product Manager",
    image: undefined,
    startDate: "2023-01-01",
    endDate: "2023-01-01",
    leaveType: "Date",
    title: "Casual Leave",
    reason: "Family event",
    status: "Approved" as const,
  },
  {
    _id: "6",
    name: "Mason",
    designation: "Product Manager",
    image: undefined,
    startDate: "2023-01-01",
    endDate: "2023-01-01",
    leaveType: "Date",
    title: "Medical Leave",
    reason: "Surgery recovery",
    status: "Approved" as const,
  },
  {
    _id: "7",
    name: "Liam",
    designation: "Senior Developer",
    image: undefined,
    startDate: "2023-01-01",
    endDate: "2023-01-01",
    leaveType: "Date",
    title: "Paternity Leave",
    reason: "Birth of child",
    status: "Approved" as const,
  },
  {
    _id: "8",
    name: "James",
    designation: "QA Engineer",
    image: undefined,
    startDate: "2023-01-01",
    endDate: "2023-01-01",
    leaveType: "Date",
    title: "Annual Leave",
    reason: "Holiday trip",
    status: "Approved" as const,
  },
  {
    _id: "9",
    name: "Sarah",
    designation: "UI/UX Designer",
    image: undefined,
    startDate: "2023-01-01",
    endDate: "2023-01-01",
    leaveType: "Date",
    title: "Casual Leave",
    reason: "Personal work",
    status: "Rejected" as const,
  },
  {
    _id: "10",
    name: "Michael",
    designation: "DevOps Engineer",
    image: undefined,
    startDate: "2023-01-01",
    endDate: "2023-01-01",
    leaveType: "Date",
    title: "Sick Leave",
    reason: "Flu symptoms",
    status: "Rejected" as const,
  },
];
